apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: knative-buildpack-demo
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        serviceAccountName: docker-hub-bot
        source:
          git:
            url: https://github.com/knative-demos/auto-detect-cf-buildpack.git
            revision: master
        template:
          name: buildpacks-cloudfoundry
          arguments:
          - name: IMAGE
            value: docker.io/danupo068/knative-buildpack-demo:latest
      revisionTemplate:
        spec:
          container:
            image: docker.io/danupo068/knative-buildpack-demo:latest
            imagePullPolicy: Always